#!/usr/bin/env python3
"""
Unit and regression tests for DVAS HTML Report Generator and Greenbone Report Format.
Ensures 100% data fidelity, complete CVE retention, strict XSS prevention, and packaging integrity.
"""

import os
import sys
import unittest
import base64
import tempfile
import xml.etree.ElementTree as ET
from pathlib import Path

# Add project root and greenbone_report_formats to path
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "greenbone_report_formats"))

from generate_html import extract_report_data, generate_html_report, parse_openvas_tags, map_severity

SAMPLE_XML_PATH = PROJECT_ROOT / "tests" / "fixtures" / "sample_openvas_report.xml"
PACKAGE_XML_PATH = PROJECT_ROOT / "greenbone_report_formats" / "greenbone_dvas_html_report_format.xml"


class TestDVASReportFormat(unittest.TestCase):

    def setUp(self):
        self.assertTrue(SAMPLE_XML_PATH.exists(), f"Sample XML file not found at: {SAMPLE_XML_PATH}")

    def test_openvas_xml_data_extraction_counts(self):
        """Verify exact extraction of 60 findings, 74 CVEs, and 5 severity categories."""
        data = extract_report_data(str(SAMPLE_XML_PATH))

        self.assertEqual(data['total_findings_count'], 60, "Expected exactly 60 total findings")
        self.assertEqual(data['unique_cves_count'], 74, "Expected exactly 74 unique CVEs")
        self.assertEqual(data['unique_hosts_count'], 1, "Expected exactly 1 scanned host")
        self.assertEqual(data['hosts'], ['192.168.4.255'])

        # Verify severity distribution
        counts = data['counts']
        self.assertEqual(counts['Critical'], 12, f"Critical findings count mismatch: {counts['Critical']}")
        self.assertEqual(counts['High'], 14, f"High findings count mismatch: {counts['High']}")
        self.assertEqual(counts['Medium'], 32, f"Medium findings count mismatch: {counts['Medium']}")
        self.assertEqual(counts['Low'], 2, f"Low findings count mismatch: {counts['Low']}")
        self.assertEqual(counts['Info'], 0, f"Info findings count mismatch: {counts['Info']}")

    def test_dvas_branding_and_zero_nessus_residue(self):
        """Verify complete removal of Tenable/Nessus brand and proper DVAS branding."""
        data = extract_report_data(str(SAMPLE_XML_PATH))
        html_out = generate_html_report(data)

        # DVAS Brand presence
        self.assertIn("DVAS", html_out, "DVAS badge not found in HTML")
        self.assertIn("SECURITY INTELLIGENCE PLATFORM", html_out)
        self.assertIn("Report generated by DVAS™", html_out)

        # Zero Tenable / Nessus residue
        self.assertNotIn("Tenable", html_out, "Tenable brand still found in HTML report")
        self.assertNotIn("Nessus", html_out, "Nessus brand still found in HTML report")
        self.assertNotIn("data:image/png;base64", html_out, "Found bloated base64 PNG in HTML")

    def test_cve_2024_4577_and_critical_vulns_retained(self):
        """Verify CVE-2024-4577 and other high-risk CVEs are preserved and linked."""
        data = extract_report_data(str(SAMPLE_XML_PATH))
        html_out = generate_html_report(data)

        self.assertIn("CVE-2024-4577", html_out, "CVE-2024-4577 missing from generated HTML")
        self.assertIn("https://nvd.nist.gov/vuln/detail/CVE-2024-4577", html_out)
        # jQuery EOL non-CVE criticals
        self.assertIn("jQuery End of Life (EOL) Detection - Windows", html_out)

    def test_stored_xss_prevention(self):
        """Verify malicious scanner output/banners and dangerous URL schemes are mitigated to prevent Stored XSS."""
        malicious_xml = """<report>
          <results>
            <result id="test-1">
              <host>10.0.0.1</host>
              <port>80/tcp</port>
              <threat>Critical</threat>
              <severity>9.5</severity>
              <name><![CDATA[<script>alert('xss_name')</script>]]></name>
              <description><![CDATA[<img src=x onerror=alert('xss_desc')>]]></description>
              <nvt oid="1.2.3.4">
                <name><![CDATA[<script>alert('xss_nvt')</script>]]></name>
                <family>Web</family>
                <tags><![CDATA[summary=<script>alert('xss_sum')</script>|insight=<b onmouseover=alert(1)>test</b>]]></tags>
                <refs>
                  <ref type="cve" id="CVE-2026-99999"/>
                  <ref type="url" id="javascript:alert('xss_url')"/>
                  <ref type="url" id="data:text/html,&lt;script&gt;alert(1)&lt;/script&gt;"/>
                  <ref type="url" id="vbscript:msgbox('xss_vb')"/>
                  <ref type="url" id="https://trusted.org/advisories/CVE-2026-99999"/>
                </refs>
              </nvt>
            </result>
          </results>
        </report>"""

        data = extract_report_data(malicious_xml)
        html_out = generate_html_report(data)

        # Ensure raw <script> or unescaped onerror is absent
        self.assertNotIn("<script>alert(", html_out, "Stored XSS vector detected in output HTML")
        self.assertNotIn("<img src=x onerror=", html_out, "Unescaped HTML injection detected in evidence box")
        self.assertIn("&lt;script&gt;alert(", html_out, "HTML escaping not applied to malicious input")

        # Verify dangerous URL schemes are not rendered as clickable href links
        self.assertNotIn('href="javascript:', html_out, "Unsafe javascript: scheme found in href")
        self.assertNotIn('href="data:', html_out, "Unsafe data: scheme found in href")
        self.assertNotIn('href="vbscript:', html_out, "Unsafe vbscript: scheme found in href")

        # Verify safe URL is properly rendered as a link
        self.assertIn('href="https://trusted.org/advisories/CVE-2026-99999"', html_out)

        # Verify unsafe URLs are rendered safely as text inside spans
        self.assertIn('<span class="unsafe-url">javascript:alert(&#x27;xss_url&#x27;)</span>', html_out)

    def test_is_safe_url_validation(self):
        """Verify is_safe_url correctly accepts valid http/https URLs and rejects unsafe schemes."""
        from generate_html import is_safe_url
        self.assertTrue(is_safe_url("https://example.com/test"))
        self.assertTrue(is_safe_url("http://192.168.1.1:8080/path?a=1&b=2"))
        self.assertFalse(is_safe_url("javascript:alert(1)"))
        self.assertFalse(is_safe_url("JAVASCRIPT:alert(1)"))
        self.assertFalse(is_safe_url("data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg=="))
        self.assertFalse(is_safe_url("vbscript:msgbox(1)"))
        self.assertFalse(is_safe_url("file:///etc/passwd"))
        self.assertFalse(is_safe_url("about:blank"))
        self.assertFalse(is_safe_url(""))
        self.assertFalse(is_safe_url(None))
        self.assertFalse(is_safe_url("   "))

    def test_package_xml_and_base64_integrity(self):
        """Verify greenbone_dvas_html_report_format.xml parses cleanly and decodes correctly."""
        self.assertTrue(PACKAGE_XML_PATH.exists(), f"Package XML not found: {PACKAGE_XML_PATH}")

        tree = ET.parse(PACKAGE_XML_PATH)
        root = tree.getroot()

        self.assertEqual(root.tag, "get_report_formats_response")
        rf = root.find("./report_format")
        self.assertIsNotNone(rf, "Missing report_format element")
        self.assertEqual(rf.get("id"), "d7a1249b-8419-482a-9e7f-619da0e7b102")
        self.assertEqual(rf.findtext("name"), "DVAS HTML Report")
        self.assertEqual(rf.findtext("extension"), "html")
        self.assertEqual(rf.findtext("content_type"), "text/html")

        # Check encoded files
        files = {f.get("name"): f.text for f in rf.findall("./file")}
        self.assertIn("generate", files)
        self.assertIn("generate_html.py", files)
        self.assertIn("report_format.xml", files)

        # Decode generate
        decoded_generate = base64.b64decode(files["generate"]).decode("utf-8")
        self.assertIn("#!/bin/sh", decoded_generate)
        self.assertIn("generate_html.py", decoded_generate)

        # Decode generate_html.py
        decoded_py = base64.b64decode(files["generate_html.py"]).decode("utf-8")
        self.assertIn("DVAS Security Intelligence Platform", decoded_py)

    def test_multi_target_dynamic_rendering(self):
        """Verify dynamic generation and grouping when scanning multiple targets simultaneously."""
        multi_host_xml = """<report>
          <task><name>Multi-Target Production Scan</name></task>
          <scan_start>2026-09-08T10:00:00Z</scan_start>
          <results>
            <result id="res-1">
              <host>192.168.1.10</host>
              <port>80/tcp</port>
              <threat>Critical</threat>
              <severity>9.8</severity>
              <name>Web Server RCE</name>
              <description>Remote code execution proof on web server</description>
              <nvt oid="1.3.6.1.1">
                <name>Web Server RCE</name>
                <family>Web Servers</family>
                <tags>summary=Remote code execution|solution=Upgrade web server to patch RCE</tags>
                <refs><ref type="cve" id="CVE-2024-4577"/></refs>
              </nvt>
            </result>
            <result id="res-2">
              <host>192.168.1.20</host>
              <port>445/tcp</port>
              <threat>High</threat>
              <severity>8.1</severity>
              <name>SMB Signing Disabled</name>
              <description>SMB signing is not required</description>
              <nvt oid="1.3.6.1.2">
                <name>SMB Signing Disabled</name>
                <family>Windows</family>
                <tags>summary=SMB signing disabled|solution=Enable SMB signing</tags>
                <refs><ref type="cve" id="CVE-2023-1234"/></refs>
              </nvt>
            </result>
            <result id="res-3">
              <host>10.0.0.50</host>
              <port>22/tcp</port>
              <threat>Medium</threat>
              <severity>5.3</severity>
              <name>SSH Weak Ciphers</name>
              <description>CBC ciphers supported</description>
              <nvt oid="1.3.6.1.3">
                <name>SSH Weak Ciphers</name>
                <family>General</family>
                <tags>summary=Weak CBC ciphers|solution=Disable CBC ciphers in sshd_config</tags>
              </nvt>
            </result>
            <result id="res-4">
              <host>192.168.1.10</host>
              <port>443/tcp</port>
              <threat>Low</threat>
              <severity>3.5</severity>
              <name>SSL Certificate Expired</name>
              <description>Certificate expired 10 days ago</description>
              <nvt oid="1.3.6.1.4">
                <name>SSL Certificate Expired</name>
                <family>SSL/TLS</family>
                <tags>summary=Expired cert|solution=Renew SSL certificate</tags>
              </nvt>
            </result>
          </results>
        </report>"""

        data = extract_report_data(multi_host_xml)
        self.assertEqual(data['unique_hosts_count'], 3, "Expected 3 unique targets")
        self.assertEqual(data['hosts'], ['10.0.0.50', '192.168.1.10', '192.168.1.20'])
        self.assertEqual(data['total_findings_count'], 4)
        self.assertEqual(data['counts']['Critical'], 1)
        self.assertEqual(data['counts']['High'], 1)
        self.assertEqual(data['counts']['Medium'], 1)
        self.assertEqual(data['counts']['Low'], 1)

        html_out = generate_html_report(data)

        # Verify Table of Contents contains all 3 targets with their finding counts
        self.assertIn('href="#host_10.0.0.50"', html_out)
        self.assertIn('href="#host_192.168.1.10"', html_out)
        self.assertIn('href="#host_192.168.1.20"', html_out)
        self.assertIn('10.0.0.50</a> (1 findings)', html_out)
        self.assertIn('192.168.1.10</a> (2 findings)', html_out)
        self.assertIn('192.168.1.20</a> (1 findings)', html_out)

        # Verify Host Headers in the main body
        self.assertIn('id="host_10.0.0.50"', html_out)
        self.assertIn('id="host_192.168.1.10"', html_out)
        self.assertIn('id="host_192.168.1.20"', html_out)

        # Verify findings are properly associated with their targets
        self.assertIn('Web Server RCE', html_out)
        self.assertIn('SMB Signing Disabled', html_out)
        self.assertIn('SSH Weak Ciphers', html_out)
        self.assertIn('SSL Certificate Expired', html_out)

        # Verify Remediations Table displays Target Host
        self.assertIn('<code>192.168.1.10</code>', html_out)
        self.assertIn('<code>192.168.1.20</code>', html_out)


if __name__ == '__main__':
    unittest.main()
